import { create } from 'zustand'

type State = {
  profileImage: string | null,
  name: string | null,
  username: string | null,
  date: string | null,
  additionalYear: boolean,
  textContent: string | null,
  tweetWidth: 'md' | 'lg' | 'xl',
  profileShape: 'square' | 'rounded' | 'circle',
  verified: 'blue' | 'gold' | 'gray' | null,
  liked: boolean,
  reposted: boolean,
  viewed: boolean,
  colorMode: 'light' | 'dark',
  repost: string | number | null,
  like: string | number | null,
  view: string | number | null,
}

type Action = {
  setProfileImage: (profileImage: string) => void,
  setName: (name: string) => void,
  setUsername: (username: string) => void,
  setDate: (date: string) => void,
  setAdditionalYear: (additionalYear: boolean) => void,
  setTextContent: (textContent: string) => void,
  setTweetWidth: (tweetWidth: 'md' | 'lg' | 'xl') => void,
  setProfileShape: (profileShape: 'square' | 'rounded' | 'circle') => void,
  setVerified: (verified: 'blue' | 'gold' | 'gray' | null) => void,
  setLiked: (liked: boolean) => void,
  setReposted: (reposted: boolean) => void,
  setViewed: (viewed: boolean) => void,
  setColorMode: (colorMode: 'light' | 'dark') => void,
  setRepost: (repost: string | number) => void,
  setLike: (like: string | number) => void,
  setView: (view: string | number) => void,
  resetState: () => void
}

const initialState: State = {
  profileImage: null,
  name: null,
  username: null,
  date: null,
  additionalYear: false,
  textContent: null,
  tweetWidth: 'md',
  profileShape: 'circle',
  verified: null,
  liked: false,
  reposted: false,
  viewed: false,
  colorMode: 'light',
  repost: null,
  like: null,
  view: null,
}

const useContentStore = create<State & Action>((set) => ({
  profileImage: null,
  name: null,
  username: null,
  date: null,
  additionalYear: false,
  textContent: null,
  tweetWidth: 'md',
  profileShape: 'circle',
  verified: null,
  liked: false,
  reposted: false,
  viewed: false,
  colorMode: 'light',
  repost: null,
  like: null,
  view: null,
  setProfileImage: (profileImage) => set({ profileImage }),
  setName: (name) => set({ name }),
  setUsername: (username) => set({ username }),
  setDate: (date) => set({ date }),
  setAdditionalYear: (additionalYear) => set({ additionalYear }),
  setTextContent: (textContent) => set({ textContent }),
  setTweetWidth: (tweetWidth) => set({ tweetWidth }),
  setProfileShape: (profileShape) => set({ profileShape }),
  setVerified: (verified) => set({ verified }),
  setLiked: (liked) => set({ liked }),
  setReposted: (reposted) => set({ reposted }),
  setViewed: (viewed) => set({ viewed }),
  setColorMode: (colorMode) => set({ colorMode }),
  setRepost: (repost) => set({ repost }),
  setLike: (like) => set({ like }),
  setView: (view) => set({ view }),
  resetState: () => set(initialState)
}))

export default useContentStore